import datetime
from fpdf import FPDF


def score_color_label(score: int) -> tuple[str, str]:
    if score >= 80: return "#2ecc71", "Agent-Ready"
    if score >= 60: return "#27ae60", "Above Average"
    if score >= 40: return "#e67e22", "Average"
    if score >= 20: return "#e74c3c", "Below Average"
    return "#c0392b", "Not Ready"


def generate_txt(result: dict) -> str:
    score = result["score"]
    _, label = score_color_label(score)
    lines = [
        "agentready Report",
        f"URL:   {result['url']}",
        f"Score: {score}/100  --  {label}",
        f"Date:  {datetime.date.today()}",
        "",
        "CHECK RESULTS",
        "-" * 52,
    ]
    for c in result["checks"]:
        s = "PASS" if c["status"] == "pass" else "WARN" if c["status"] == "warning" else "FAIL"
        lines.append(f"[{s}] {c['check']} -- {c['points_earned']}/{c['points_max']} pts")
        lines.append(f"  Finding: {c['detail']}")
        if c["status"] != "pass":
            lines.append(f"  Fix:     {c['action']}")
    if result.get("recommendations"):
        lines += ["", "", "PRIORITISED FIX LIST", "-" * 52]
        for i, r in enumerate(result["recommendations"], 1):
            lines.append(f"{i}. {r['check']}  (+{r['points_lost']} pts)  |  {r['effort_level']} - {r['effort_time']}")
            lines.append(f"   {r['action']}")
    subpages = result.get("subpages", {})
    if subpages:
        lines += ["", "", "SUB-PAGE ANALYSIS", "-" * 52]
        for page_type, data in subpages.items():
            lines.append(f"[{page_type.upper()}] {data['url']}")
            for key, res in data.items():
                if key == "url":
                    continue
                s = "PASS" if res.get("pass") is True else "WARN" if res.get("pass") is None else "FAIL"
                lines.append(f"  [{s}] {key}: {res['detail']}")
    lines += ["", "-" * 52, "Generated by agentready - github.com/mohanishmhatre/agentready"]
    return "\n".join(lines)


_CHAR_MAP = [
    ("–", "-"), ("—", "-"),
    ("‘", "'"), ("’", "'"),
    ("“", '"'), ("”", '"'),
    ("…", "..."),
]


def _clean(s: str) -> str:
    for bad, good in _CHAR_MAP:
        s = s.replace(bad, good)
    return s.encode("latin-1", errors="replace").decode("latin-1")


def generate_pdf(result: dict) -> bytes:
    score = result["score"]
    _, label = score_color_label(score)
    W = 190

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(W, 12, "agentready Report", ln=True, align="C")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(W, 6, "AI Agent Readiness Scanner", ln=True, align="C")
    pdf.ln(4)

    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(W, 7, _clean(f"URL:   {result['url']}"))
    pdf.multi_cell(W, 7, _clean(f"Score: {score}/100  ({label})"))
    pdf.multi_cell(W, 7, f"Date:  {datetime.date.today()}")
    pdf.ln(4)

    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)

    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(W, 8, "Check Results", ln=True)
    pdf.ln(2)

    for c in result["checks"]:
        tag = {"pass": "[PASS]", "warning": "[WARN]", "fail": "[FAIL]"}[c["status"]]
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(0, 0, 0)
        pdf.multi_cell(W, 6, _clean(f"{tag} {c['check']} -- {c['points_earned']}/{c['points_max']} pts  |  {c['effort_level']} - {c['effort_time']}"))
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(70, 70, 70)
        pdf.multi_cell(W, 5, _clean(c["detail"]))
        if c["status"] != "pass":
            pdf.set_text_color(150, 80, 0)
            pdf.multi_cell(W, 5, _clean("Fix: " + c["action"]))
            pdf.set_text_color(0, 0, 0)
        pdf.ln(3)

    if result.get("recommendations"):
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(W, 8, "Prioritised Fix List", ln=True)
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(120, 120, 120)
        pdf.cell(W, 6, "Sorted by points available - highest ROI first.", ln=True)
        pdf.ln(2)
        for i, rec in enumerate(result["recommendations"], 1):
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(0, 0, 0)
            pdf.multi_cell(W, 6, _clean(f"{i}. {rec['check']}  (+{rec['points_lost']} pts)  |  {rec['effort_level']} - {rec['effort_time']}"))
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(70, 70, 70)
            pdf.multi_cell(W, 5, _clean(rec["action"]))
            pdf.ln(3)

    pdf.set_y(-15)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(160, 160, 160)
    pdf.cell(W, 10, "Generated by agentready - github.com/mohanishmhatre/agentready", align="C")
    return bytes(pdf.output())
